name: .NET Core CI

on:
  push:
    branches: [ main , develop ]
  pull_request:
    branches: [ main , develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x 
        
    - name: Restore dependencies
      run: dotnet restore SecurityAPI.sln

    - name: Build
      run: dotnet build SecurityAPI.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test SecurityAPI.sln --no-build --verbosity normal
