version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run Tests 
          command: echo "There are no tests yet."
      - run:
          name: Install Sonar Scanner locally
          command: npm install sonar-scanner --save-dev
      - run:
          name: Run SonarQube Scan
          command: |
            npx sonar-scanner \
              -Dsonar.projectKey=my_project_key \
              -Dsonar.organization=my_org_key \
              -Dsonar.sources=. \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
