version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  sonarcloud-analysis:
    docker:
      - image: cimg/node:18.17
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci || npm install
      - run:
          name: Install Sonar Scanner
          command: npm install sonar-scanner --save-dev
      - run:
          name: Run SonarCloud Scan
          command: |
            npx sonar-scanner \
              -Dsonar.projectKey=<your_project_key_here> \
              -Dsonar.organization=<your_org_key_here> \
              -Dsonar.sources=. \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - sonarcloud-analysis:
          context: SonarCloud

